# BetterHomes Server Configuration
# Please restart the Server to apply the Config

# Enables/Disables the mod completely (boolean: true/false)
homes-enabled: true

# Maximum number of Homes a player can have (Integer: 1 - 2147483647)
max-homes: 4

# Allows players to teleport to their Homes if they are in another world
allow-cross-world-teleportation: false